name: DoThanhDat
options:
  bundleIdPrefix: com.dothanhdat
  deploymentTarget:
    iOS: "16.0"
targets:
  DoThanhDat:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DoThanhDat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dothanhdat.profile
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_CFBundleDisplayName: "Đỗ Thành Đạt"
